apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ app_name }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
spec:
  replicas: {{ replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ app_name }}
      app.kubernetes.io/instance: {{ app_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ app_name }}
        app.kubernetes.io/instance: {{ app_name }}
    spec:
      containers:
        - name: {{ app_name }}
          image: quay.io/hadrienpatte/com.example.hello
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ app_port }}
              protocol: TCP
            - name: actuator
              containerPort: {{ actuator_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: actuator
