apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}
  labels:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
spec:
  type: {{ service_type }}
  ports:
    - name: http
      port: {{ service_port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ app_name }}
    app.kubernetes.io/instance: {{ app_name }}
